In [112]:
import pandas as pd

data1=pd.read_csv("newtest.csv")

data1

    S.N.               Name  Contact No.  Year             Address
0      1     Mohit Tripathi   8887331179   2nd           Prayagraj
1      2        Jay Narayan   9511493970   3rd           Sultanpur
2      3           Aman Pal   9151503447   2nd             Jaunpur
3      4         Nikhil Rai   9305080327   2nd  Maunath Bhajan Mau
4      5       Sonush Kumar   8400716124   2nd          Shajahapur
5      6        Vivek Kumar   9151480914   3rd           Sonbhadra
6      7      Pranshu Dubey   8707037056   2nd            Mirzapur
7      8       Vishal Kumar   8273730104   3rd            Bareilly
8      9       Sujeet Kumar   9565256344   2nd              Ballia
9     10        Niraj Kumar   7310362981   NaN              Ballia
10    11        Mohit Yadav   9721334026   2nd      Ambedkar Nagar
11    12   Himanshu Katiyar   9897515619   2nd            Bareilly
12    13       Mayank Singh   8960959096   NaN         RaeBareilly
13    14       Shivam Kumar   8102375878   3rd               Patna
14    15  Kishan Raghuvansh   7451099204   2nd     Khitaura Badaun
15    16       Aditya Kumar   7645071129   2nd          Gaya Bihar
16    17         Farman Ali   9027969463  4rth            Bareilly
17    18              Arpit   8853029377   2nd             Jaunpur
18    19        Laki Sharma   8267968235   2nd         TiliyaKhata
19    20     Utkarsh Sharma   7317762256   2nd         Shajahanpur
20    21              Akash   7398558431   NaN                 Mau
21    22       Vikash Yadav   8115514548  4rth              Ballia
22    23         Ashu Yadav   8115191992   2nd                 Mau
23    24            Shivraj   8409108148   2nd                 Mau
24    25      Karan Bhrdwaj   9795590870  4rth          Farukhabad
25    26        Anuj Gautam   8601097943   2nd              Kanpur
26    27        Ankit Kumar   7817895076  4rth            Bareilly
27    28        Arjun Singh   9389454010   2nd            Bareilly
28    29   Prince Prajapati   7800170358   3rd           Gorakhpur

In [113]:
data1.replace(to_replace="2nd",value="4rth")
# data1.replace("2nd","4rth")

    S.N.               Name  Contact No.  Year             Address
0      1     Mohit Tripathi   8887331179  4rth           Prayagraj
1      2        Jay Narayan   9511493970   3rd           Sultanpur
2      3           Aman Pal   9151503447  4rth             Jaunpur
3      4         Nikhil Rai   9305080327  4rth  Maunath Bhajan Mau
4      5       Sonush Kumar   8400716124  4rth          Shajahapur
5      6        Vivek Kumar   9151480914   3rd           Sonbhadra
6      7      Pranshu Dubey   8707037056  4rth            Mirzapur
7      8       Vishal Kumar   8273730104   3rd            Bareilly
8      9       Sujeet Kumar   9565256344  4rth              Ballia
9     10        Niraj Kumar   7310362981   NaN              Ballia
10    11        Mohit Yadav   9721334026  4rth      Ambedkar Nagar
11    12   Himanshu Katiyar   9897515619  4rth            Bareilly
12    13       Mayank Singh   8960959096   NaN         RaeBareilly
13    14       Shivam Kumar   8102375878   3rd               Patna
14    15  Kishan Raghuvansh   7451099204  4rth     Khitaura Badaun
15    16       Aditya Kumar   7645071129  4rth          Gaya Bihar
16    17         Farman Ali   9027969463  4rth            Bareilly
17    18              Arpit   8853029377  4rth             Jaunpur
18    19        Laki Sharma   8267968235  4rth         TiliyaKhata
19    20     Utkarsh Sharma   7317762256  4rth         Shajahanpur
20    21              Akash   7398558431   NaN                 Mau
21    22       Vikash Yadav   8115514548  4rth              Ballia
22    23         Ashu Yadav   8115191992  4rth                 Mau
23    24            Shivraj   8409108148  4rth                 Mau
24    25      Karan Bhrdwaj   9795590870  4rth          Farukhabad
25    26        Anuj Gautam   8601097943  4rth              Kanpur
26    27        Ankit Kumar   7817895076  4rth            Bareilly
27    28        Arjun Singh   9389454010  4rth            Bareilly
28    29   Prince Prajapati   7800170358   3rd           Gorakhpur

In [114]:
# data1.replace([1,2,3,4,5,6,7,9,22],455)
# data1.replace("2nd",577)

In [115]:
# data1.replace("[A-Za-z]","Python",regex=True)
# data1.replace("[A-F]","panda",regex=True)
# data1.replace("[A-Fa-z]","panda",regex=True)
# data1.replace("[0-9]","panda",regex=True)

In [116]:
data1.replace({"Year":"2nd"},56,regex=True)

    S.N.               Name  Contact No.  Year             Address
0      1     Mohit Tripathi   8887331179    56           Prayagraj
1      2        Jay Narayan   9511493970   3rd           Sultanpur
2      3           Aman Pal   9151503447    56             Jaunpur
3      4         Nikhil Rai   9305080327    56  Maunath Bhajan Mau
4      5       Sonush Kumar   8400716124    56          Shajahapur
5      6        Vivek Kumar   9151480914   3rd           Sonbhadra
6      7      Pranshu Dubey   8707037056    56            Mirzapur
7      8       Vishal Kumar   8273730104   3rd            Bareilly
8      9       Sujeet Kumar   9565256344    56              Ballia
9     10        Niraj Kumar   7310362981   NaN              Ballia
10    11        Mohit Yadav   9721334026    56      Ambedkar Nagar
11    12   Himanshu Katiyar   9897515619    56            Bareilly
12    13       Mayank Singh   8960959096   NaN         RaeBareilly
13    14       Shivam Kumar   8102375878   3rd               Patna
14    15  Kishan Raghuvansh   7451099204    56     Khitaura Badaun
15    16       Aditya Kumar   7645071129    56          Gaya Bihar
16    17         Farman Ali   9027969463  4rth            Bareilly
17    18              Arpit   8853029377    56             Jaunpur
18    19        Laki Sharma   8267968235    56         TiliyaKhata
19    20     Utkarsh Sharma   7317762256    56         Shajahanpur
20    21              Akash   7398558431   NaN                 Mau
21    22       Vikash Yadav   8115514548  4rth              Ballia
22    23         Ashu Yadav   8115191992    56                 Mau
23    24            Shivraj   8409108148    56                 Mau
24    25      Karan Bhrdwaj   9795590870  4rth          Farukhabad
25    26        Anuj Gautam   8601097943    56              Kanpur
26    27        Ankit Kumar   7817895076  4rth            Bareilly
27    28        Arjun Singh   9389454010    56            Bareilly
28    29   Prince Prajapati   7800170358   3rd           Gorakhpur

In [117]:
# data1.replace("Mau",axis=0)
# data1.replace("Mau",method="ffill",limit=1)
# data1.replace("Mau",method="ffill",limit=1,inplace=True) # changes original data 
# data1.replace("Mau",method="bfill",limit=1)

In [118]:
import pandas as pd

data1=pd.read_csv("newtest.csv")
data1

    S.N.               Name  Contact No.  Year             Address
0      1     Mohit Tripathi   8887331179   2nd           Prayagraj
1      2        Jay Narayan   9511493970   3rd           Sultanpur
2      3           Aman Pal   9151503447   2nd             Jaunpur
3      4         Nikhil Rai   9305080327   2nd  Maunath Bhajan Mau
4      5       Sonush Kumar   8400716124   2nd          Shajahapur
5      6        Vivek Kumar   9151480914   3rd           Sonbhadra
6      7      Pranshu Dubey   8707037056   2nd            Mirzapur
7      8       Vishal Kumar   8273730104   3rd            Bareilly
8      9       Sujeet Kumar   9565256344   2nd              Ballia
9     10        Niraj Kumar   7310362981   NaN              Ballia
10    11        Mohit Yadav   9721334026   2nd      Ambedkar Nagar
11    12   Himanshu Katiyar   9897515619   2nd            Bareilly
12    13       Mayank Singh   8960959096   NaN         RaeBareilly
13    14       Shivam Kumar   8102375878   3rd               Patna
14    15  Kishan Raghuvansh   7451099204   2nd     Khitaura Badaun
15    16       Aditya Kumar   7645071129   2nd          Gaya Bihar
16    17         Farman Ali   9027969463  4rth            Bareilly
17    18              Arpit   8853029377   2nd             Jaunpur
18    19        Laki Sharma   8267968235   2nd         TiliyaKhata
19    20     Utkarsh Sharma   7317762256   2nd         Shajahanpur
20    21              Akash   7398558431   NaN                 Mau
21    22       Vikash Yadav   8115514548  4rth              Ballia
22    23         Ashu Yadav   8115191992   2nd                 Mau
23    24            Shivraj   8409108148   2nd                 Mau
24    25      Karan Bhrdwaj   9795590870  4rth          Farukhabad
25    26        Anuj Gautam   8601097943   2nd              Kanpur
26    27        Ankit Kumar   7817895076  4rth            Bareilly
27    28        Arjun Singh   9389454010   2nd            Bareilly
28    29   Prince Prajapati   7800170358   3rd           Gorakhpur

In [119]:
# data1.infer_objects(copy=False)
# data1.interpolate()

In [120]:

# data1.interpolate(method="index")
# data1.interpolate(method="index",axis=0)
# data1.interpolate(method="index",limit=4)

In [ ]:
import pandas as pd

data1=pd.read_csv("newtest2.csv")
data1
# data1.interpolate(method="index",limit=2,limit_direction="backward")
# data1.interpolate(method="index",limit=2,limit_direction="both")
# data1.interpolate(limit_area="inside")
# data1.interpolate(limit_area="outside")

TypeError: Cannot interpolate with str dtype